### ISSUE TITLE
Recommendation of our recent paper. 

### ISSUE THREAD

**Issue by jizongFox** [SaeedShurrab/awesome-self-supervised-learning-in-medical-imaging#2]
Hello, 
I came across your repo, and it seems to be a good summary of recent advance in Medical image with self-supervised learning. 

Here I would like to recommend a recent paper from my group, which addresses uniquely the pretraining for decoder of a segmentation network. This work does not belong to contrastive or predictive categories and may be interesting to have more publicity. 

Thanks for considering adding it into your list. 

https://arxiv.org/abs/2202.02371

**Comment by SaeedShurrab** [comment]
Hi dear,

I will review the paper and add it if possible,

Meanwhile, kindly star and share the repo,

**Comment by jizongFox** [comment]
Stared, thank you. If you have any question regarding the methodology of this paper, feel free to contact me.

**Comment by SaeedShurrab** [comment]
thanks,

is it submitted to any Journal ad being reviewed??

**Comment by jizongFox** [comment]
Under review of a top conference.

**Comment by SaeedShurrab** [comment]
Nice, I wish you good luck with your submission, in the meantime, I am a bit busy and need to read at least the introduction and methodology before listing the paper. I will do that whenever I have free time.
