### ISSUE TITLE
Recommend our work with codes available.

### ISSUE THREAD

**Issue by yjump** [SaeedShurrab/awesome-self-supervised-learning-in-medical-imaging#3]
Good job, bro. I would like to share our recent work [Towards better understanding and better generalization of few-shot classification in histology images with contrastive learning] (https://arxiv.org/abs/2202.09059) which has been published with ICLR2022 and codes available in https://github.com/TencentAILabHealthcare/Few-shot-WSI

I have starred this repo. Thanks for your collections.

**Comment by SaeedShurrab** [comment]
Hi Jack,

Is there a link to the published version rather than ArXive preprint?

**Comment by yjump** [comment]
Hi Shurrab,

Our work is published at openreview at https://openreview.net/forum?id=kQ2SOflIOVC with detailed review process. Thanks.

**Comment by SaeedShurrab** [comment]
Done and dusted
